### ISSUE TITLE
show_admin_bar fails

### ISSUE THREAD

**Issue by Mattronica** [andjosh/naked-wordpress#4]
Hey - love the theme

When adding show_admin_bar to the functions.php the page is not displayed correctly. 

Just add the below to your functions.php to recreate
```php
add_filter('show_admin_bar', '__return_false');
```
Best
Matt

**Comment by andjosh** [comment]
In which version of WordPress did you find this issue?

It seems to have been replaced with "Toolbar" http://codex.wordpress.org/Function_Reference/show_admin_bar#Description
