### ISSUE TITLE
No sidebar

### ISSUE THREAD

**Issue by Masquetina** [andjosh/naked-wordpress#8]
It's just not working. Widgets and the whole sidebar are not showing up on the page. Please, help?
Thanks

**Comment by Masquetina** [comment]
Silly me, I just needed to add one function where I wanted the sidebar, *<?php get_sidebar(); ?>* of course. Sorry, I'm new to WordPress, so I panicked.

**Comment by andjosh** [comment]
No worries! That's what this project is for. You can open up another issue if you need help.

**Comment by Masquetina** [comment]
Ok, thanks. :+1:

**Comment by Linon419** [comment]
Silly me, how to add it?

**Comment by Linon419** [comment]
> Silly me, how to add it?

<?php get_sidebar(); ?>
Thanks
